
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UBITIPT
{

using System;
    using System.Collections.Generic;
    
public partial class Branch
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Branch()
    {

        this.OrderStatus = new HashSet<OrderStatu>();

    }


    public int Id { get; set; }

    public string BranchName { get; set; }

    public string BranchManager { get; set; }

    public string BranchAddress { get; set; }

    public string BranchContact { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderStatu> OrderStatus { get; set; }

}

}
